######
#Qanbari Creeping Windows 
######



#Creeping Window Analyses based on Qanbari et al. (2012; PLOS ONE) 
	#http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0049525
	#This script takes in a data frame of Fst values for each position in A SINGLE chromosome/scaffold (henceforth "region")
	#The script divides the region into equal bp windows and places SNPs into their appropriate windows
	#For each window, it then scans 
	#Also outputs 2 plots to help trim windows based on the number of SNPs included in them 
		#NumSNPsbyBin.png - plots the variation in FST per bin (bin is a bin of window lengths)
		#SDbyBin.png - plots the average variation in FST per bin 
	
	
#Data must be in data frame format with 3 columns corresponding to region, position, and fst value IN THAT ORDER!
	#	       chr1 156 0.00070403
	#	       chr1 203 0.00008735
	#					...
	#	       chr1 22552003 0.00007730
	
	

# Declare Variables ----------------------------
window.size = 5000 #size of window to be crept and gaps to skip, in BP 
bin.size = 6 # minimum number of SNPs in a window (bin size, see plot)
signi = 0.01 #significance cutoff for high windows 
fst.frame =  #insert name of data frame of fst, as above

	
# Load Required Functions and Pakcages ------------------------
library(IRanges)
library(Hmisc)
library(ggplot2)
library(plyr)
library(reshape2)
library(RColorBrewer)
library(scales)
source("Q_correct.r")



perm.creeper <-function(n=999,  num=num, fst=creeper$fstHvL){
	#estimates perm likelihood of given SNP window generated by creeper script
	#draws SNPs within clusters to account for linkage effects
	vec=rep(0,n)
	for (i in 1:n){
		size = sample(num, 1, replace=TRUE)
		len = length(fst)-size
		samp = sample(c(1:len), 1, replace=T)
		ran = samp:(samp+size-1)
		x = mean(fst[ran])
		vec[i]=x
	}
	vec

}


creeper<-function(fst.frame, window.size ){
	names(fst.frame) = c("V2", "POS", "fst45")
	#Gather SNPs and FST as numeric variables
	snp = as.numeric(fst.frame$POS)
	fst = as.numeric(fst.frame$fst45)
	#estimate difference between SNPs	
	p = as.numeric(fst.frame$POS[fst.frame$V2==k])
	p = p[-1]
	p = c(p, NA)
	diff = abs(as.numeric(fst.frame$POS[fst.frame$V2==k])-p)
	diff = diff[!is.na(diff)]

	x=rep(0, (max(snp)+ window.size))
	x[snp]=1
	x=cumsum(x)
	endsnp=x[snp+ window.size]
	n=length(fst)
	vec=rep(0,n)
	len=rep(0,n)
	end=rep(0,n)

	for (i in 1:(n-1)){
			if (diff[i] < window.size ){
				snp_len=length(fst[i:endsnp[i]]) #number of SNPs per window
				fst_mean=mean(fst[i:endsnp[i]]) #mean FST per window
				vec[i]=fst_mean
				len[i]=snp_len
				end[i]=(snp[endsnp[i]])
				
			}else{
				vec[i]=NA
				len[i]=NA
				end[i]=(snp[endsnp[i]])
			}
	}
	creeper = data.frame(cbind(vec,len, snp, end))
	names(creeper)=c("fst","num_snps", "start", "end")
	creeper = creeper[which(complete.cases(creeper$num_snps)),] #remove windows with no SNPs 
	creeper = creeper[which(creeper$num_snps>0),]
	return(creeper)
}



# run Creeper ----------------------------

creep.all = creeper(fst.frame, window.size)




# Trim windows with too few SNPs -----------------------------
	#I find that the reliability of FST calls per window is dependant on the number of SNPs. 
	#I provide 2 tools to trim on window size
	#This lets you find a cut-off for minimum window size
	#I've not yet automated this, but choose the bin that has consistent variation

len = round(max(creep.all$num_snps)/10) 
creep.all$bin <- as.numeric(cut2(creep.all$num_snps, g=len))
var.plot = aggregate(creep.all$fstHvL, by = list(creep.all$bin), sd)


png(file="NumSNPsbyBin.png")
	plot(creep.all$bin, creep.all$fstHvL)
dev.off()


png(file="SDbyBin.png")
	plot(var.plot,pch=16)
dev.off()


creeper = creep.all
creeper=creeper[(creeper$bin > bin.size),]


#Significance Testing ---------------------------------------------
	# Permutation fst.frame
		#selects random window size from distribution of window sizes in data (W)
		# selects W SNPs beside each other
		#estimates mean FST of those random SNPs
		#repeats N times 
	#corrects for multiple testing  with Q test (Storey Method)
num = creeper$num_snps
lec=perm.creeper(n=100000, num=num)
creeper$pnorm.fst=pnorm(creeper$fstHvL, mean=mean(lec), sd=sd(lec),lower.tail=F)
creeper$q=qvalue1(creeper$pnorm.fst)$q
save.image("creeper.RData")